### ISSUE TITLE
a PTX JIT compilation failed

### ISSUE THREAD

**Issue by cherryxiongyw** [multimodallearning/pytorch-mask-rcnn#1]
Hello, when I train, I have an error likes this:
`
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/THC/generic/THCStorage.cu line=58 error=78 : a PTX JIT compilation failed
Traceback (most recent call last):
  File "coco.py", line 374, in <module>
    model_dir=args.logs)
  File "/home/amax/Codes/pytorch-mask-rcnn/model.py", line 1416, in __init__
    self.build(config=config)
  File "/home/amax/Codes/pytorch-mask-rcnn/model.py", line 1450, in build
    self.anchors = self.anchors.cuda()
  File "/home/amax/anaconda2/envs/py3/lib/python3.6/site-packages/torch/autograd/variable.py", line 298, in cuda
    return CudaTransfer.apply(self, device, async)
  File "/home/amax/anaconda2/envs/py3/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py", line 201, in forward
    return i.cuda(async=async)
  File "/home/amax/anaconda2/envs/py3/lib/python3.6/site-packages/torch/_utils.py", line 69, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/home/amax/anaconda2/envs/py3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 387, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: cuda runtime error (78) : a PTX JIT compilation failed at /opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/THC/generic/THCStorage.cu:58
`
how to solve it?

**Comment by lasseha** [comment]
Sorry, i did not see this error with CUDA 8.0 and the tested GPUs (GTX 1080 TI and GTX 1070). Maybe you could provide more information about your setup.

**Comment by lasseha** [comment]
Reopen if the error persists.
