### ISSUE TITLE
when installed all, I run python3 demo.py in terminal, nms/_ext/nms/_nms.so: undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by QianLingjun** [multimodallearning/pytorch-mask-rcnn#102]
qlj@zyyl-PowerEdge-T630:~/projects/pytorch-mask-rcnn$ python3 demo.py                                                                                  
Traceback (most recent call last):                                                                                                                     
  File "demo.py", line 10, in <module>                                                                                                                 
    import coco                                                                                                                                        
  File "/home/qlj/projects/pytorch-mask-rcnn/coco.py", line 50, in <module>                                                                            
    import model as modellib                                                                                                                           
  File "/home/qlj/projects/pytorch-mask-rcnn/model.py", line 26, in <module>                                                                           
    from nms.nms_wrapper import nms                                                                                                                    
  File "/home/qlj/projects/pytorch-mask-rcnn/nms/nms_wrapper.py", line 11, in <module>                                                                 
    from nms.pth_nms import pth_nms                                                                                                                    
  File "/home/qlj/projects/pytorch-mask-rcnn/nms/pth_nms.py", line 2, in <module>                                                                      
    from ._ext import nms                                                                                                                              
  File "/home/qlj/projects/pytorch-mask-rcnn/nms/_ext/nms/__init__.py", line 3, in <module>                                                            
    from ._nms import lib as _lib, ffi as _ffi                                                                                                         
ImportError: /home/qlj/projects/pytorch-mask-rcnn/nms/_ext/nms/_nms.so: undefined symbol: __cudaPopCallConfiguration               

what happen and how can address my problem.Thinks

**Comment by f-thirty** [comment]
请问_ext是怎么得到的

**Comment by LeiyuanMa** [comment]
you can try a docker with cuda9.0 installed, for me, nvidia/cuda:9.0-cudnn7-devel works.

**Comment by JCZ404** [comment]
you can install torch0.4.0+cuda9.0, it works well on my machine, but you should be careful that your machine must have enough GPU memory.

**Comment by asd646942825** [comment]
Can I fix this by recompiling PyTorch？
