### ISSUE TITLE
Error in demo.py: IndexError: trying to index 2 dimensions of a 0 dimensional tensor

### ISSUE THREAD

**Issue by omkar13** [multimodallearning/pytorch-mask-rcnn#14]
I used pretrained weights and I have received the above error. The error is seen for some images. For others, the code runs perfectly. I have no clue how to solve it. Could someone please help me? I have used the code from the github repo.

Traceback (most recent call last):
File "/home/omkar/pycharm-community-2017.3.4/helpers/pydev/pydev_run_in_console.py", line 53, in run_file
pydev_imports.execfile(file, globals, locals) # execute the script
File "/home/omkar/pycharm-community-2017.3.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "/home/omkar/PycharmProjects/mask_rcnn/demo.py", line 149, in
result = model.detect([image])
File "/home/omkar/PycharmProjects/mask_rcnn/model.py", line 1599, in detect
detections, mrcnn_mask = self.predict([molded_images, image_metas], mode='inference')
File "/home/omkar/PycharmProjects/mask_rcnn/model.py", line 1674, in predict
detections = detection_layer(self.config, rpn_rois, mrcnn_class, mrcnn_bbox, image_metas)
File "/home/omkar/PycharmProjects/mask_rcnn/model.py", line 842, in detection_layer
detections = refine_detections(rois, mrcnn_class, mrcnn_bbox, window, config)
File "/home/omkar/PycharmProjects/mask_rcnn/model.py", line 787, in refine_detections
keep = torch.nonzero(keep_bool)[:,0]
File "/home/omkar/anaconda3/envs/mask_rcnn/lib/python3.6/site-packages/torch/autograd/variable.py", line 78, in getitem
return Index.apply(self, key)
File "/home/omkar/anaconda3/envs/mask_rcnn/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py", line 89, in forward
result = i.index(ctx.index)
IndexError: trying to index 2 dimensions of a 0 dimensional tensor

Thanking you in anticipation.
Regards,
Omkar.

**Comment by xllau** [comment]
Check your pytorch version, when I use 0.4, it come the same. Change back to 0.3.1, it solved.

**Comment by AdVetter** [comment]
It is because no detections are made. 
To reproduce just use a complete white image.

**Comment by martinschnurer** [comment]
> Check your pytorch version, when I use 0.4, it come the same. Change back to 0.3.1, it solved.

Unfortunatelly, It doesn't solve the problem.

Does anyone solves this or successfuly made workaround ?

**Comment by jxw950605** [comment]
> I used pretrained weights and I have received the above error. The error is seen for some images. For others, the code runs perfectly. I have no clue how to solve it. Could someone please help me? I have used the code from the github repo.
> 
> Traceback (most recent call last):
> File "/home/omkar/pycharm-community-2017.3.4/helpers/pydev/pydev_run_in_console.py", line 53, in run_file
> pydev_imports.execfile(file, globals, locals) # execute the script
> File "/home/omkar/pycharm-community-2017.3.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
> exec(compile(contents+"\n", file, 'exec'), glob, loc)
> File "/home/omkar/PycharmProjects/mask_rcnn/demo.py", line 149, in
> result = model.detect([image])
> File "/home/omkar/PycharmProjects/mask_rcnn/model.py", line 1599, in detect
> detections, mrcnn_mask = self.predict([molded_images, image_metas], mode='inference')
> File "/home/omkar/PycharmProjects/mask_rcnn/model.py", line 1674, in predict
> detections = detection_layer(self.config, rpn_rois, mrcnn_class, mrcnn_bbox, image_metas)
> File "/home/omkar/PycharmProjects/mask_rcnn/model.py", line 842, in detection_layer
> detections = refine_detections(rois, mrcnn_class, mrcnn_bbox, window, config)
> File "/home/omkar/PycharmProjects/mask_rcnn/model.py", line 787, in refine_detections
> keep = torch.nonzero(keep_bool)[:,0]
> File "/home/omkar/anaconda3/envs/mask_rcnn/lib/python3.6/site-packages/torch/autograd/variable.py", line 78, in getitem
> return Index.apply(self, key)
> File "/home/omkar/anaconda3/envs/mask_rcnn/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py", line 89, in forward
> result = i.index(ctx.index)
> IndexError: trying to index 2 dimensions of a 0 dimensional tensor
> 
> Thanking you in anticipation.
> Regards,
> Omkar.

Hi~ do you solve this problem?

**Comment by jxw950605** [comment]
> > Check your pytorch version, when I use 0.4, it come the same. Change back to 0.3.1, it solved.
> 
> Unfortunatelly, It doesn't solve the problem.
> 
> Does anyone solves this or successfuly made workaround ?

do you solve this problem? I have the same problem.
