### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by zhanvwei** [multimodallearning/pytorch-mask-rcnn#18]
Traceback (most recent call last):
  File "/home/PycharmProjects/models/pytorch-mask-rcnn/demo.py", line 10, in <module>
    import coco
  File "/home/PycharmProjects/models/pytorch-mask-rcnn/coco.py", line 50, in <module>
    import model as modellib
  File "/home/PycharmProjects/models/pytorch-mask-rcnn/model.py", line 26, in <module>
    from nms.nms_wrapper import nms
  File "/home/PycharmProjects/models/pytorch-mask-rcnn/nms/nms_wrapper.py", line 11, in <module>
    from nms.pth_nms import pth_nms
  File "/home/PycharmProjects/models/pytorch-mask-rcnn/nms/pth_nms.py", line 2, in <module>
    from ._ext import nms
  File "/home/PycharmProjects/models/pytorch-mask-rcnn/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: /home/PycharmProjects/models/pytorch-mask-rcnn/nms/_ext/nms/_nms.so: undefined symbol: PyInt_FromLong

**Comment by lasseha** [comment]
Did you follow step 2 in the installation guide?

**Comment by dlliyang** [comment]
how to slove it!!!

**Comment by dl-lengyan** [comment]
How to slove it?Thank u

**Comment by ZHHJemotion** [comment]
@lasseha I did follow the step 2 in the installation guide, but the same problem, do you have any suggestions to resolve it? Thank you!  My pytorch version is 0.4, CUDA is 8.0
