### ISSUE TITLE
hard-to-solve problem happens when applying new trained model on evaluation

### ISSUE THREAD

**Issue by buaaMars** [multimodallearning/pytorch-mask-rcnn#33]
I train the model on COCO  for several epochs. I load one of the models got during training by  changing the model_path in coco.py and it works apparently. 
But errors happened in model.py, in refine_detections
`    keep = torch.nonzero(keep_bool)[:,0]`

> IndexError: trying to index 2 dimensions of a 0 dimensional tensor

The problem is that all the elements in keep_bool is zero. It results in a 

> torch.cuda.LongTensor with no dimension

output of `torch.nonzero(keep_bool)`.

I've noticed that codes latter use keep.data as a index of list for many times, so I guess it's really hard to make up here.
I want to confirm is it true that the all-zero keep_bool should not happens in your design?

**Comment by bigtreeljc** [comment]
same problem overhere
Checkpoint Path: /home/bigtree/PycharmProjects/pytorch-mask-rcnn/logs/coco20180707T1023/mask_rcnn_coco_{:04d}.pth
Epoch 1/40.
/home/bigtree/anaconda3/envs/tensorflow/lib/python3.6/site-packages/scipy/misc/pilutil.py:482: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if issubdtype(ts, int):
/home/bigtree/anaconda3/envs/tensorflow/lib/python3.6/site-packages/scipy/misc/pilutil.py:482: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if issubdtype(ts, int):
/home/bigtree/anaconda3/envs/tensorflow/lib/python3.6/site-packages/scipy/misc/pilutil.py:482: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if issubdtype(ts, int):
/home/bigtree/anaconda3/envs/tensorflow/lib/python3.6/site-packages/scipy/misc/pilutil.py:485: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif issubdtype(type(size), float):
/home/bigtree/anaconda3/envs/tensorflow/lib/python3.6/site-packages/scipy/misc/pilutil.py:485: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif issubdtype(type(size), float):
/home/bigtree/anaconda3/envs/tensorflow/lib/python3.6/site-packages/scipy/misc/pilutil.py:485: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif issubdtype(type(size), float):
/home/bigtree/anaconda3/envs/tensorflow/lib/python3.6/site-packages/scipy/misc/pilutil.py:482: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if issubdtype(ts, int):
/home/bigtree/anaconda3/envs/tensorflow/lib/python3.6/site-packages/scipy/misc/pilutil.py:485: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif issubdtype(type(size), float):
/home/bigtree/anaconda3/envs/tensorflow/lib/python3.6/site-packages/scipy/ndimage/interpolation.py:600: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
/home/bigtree/anaconda3/envs/tensorflow/lib/python3.6/site-packages/scipy/ndimage/interpolation.py:600: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
Traceback (most recent call last):
  File "coco.py", line 498, in <module>
    layers='heads')
  File "/home/bigtree/PycharmProjects/pytorch-mask-rcnn/model.py", line 1793, in train_model
    loss, loss_rpn_class, loss_rpn_bbox, loss_mrcnn_class, loss_mrcnn_bbox, loss_mrcnn_mask = self.train_epoch(train_generator, optimizer, self.config.STEPS_PER_EPOCH)
  File "/home/bigtree/PycharmProjects/pytorch-mask-rcnn/model.py", line 1855, in train_epoch
    self.predict([images, image_metas, gt_class_ids, gt_boxes, gt_masks], mode='training')
  File "/home/bigtree/PycharmProjects/pytorch-mask-rcnn/model.py", line 1714, in predict
    detection_target_layer(rpn_rois, gt_class_ids, gt_boxes, gt_masks, self.config)
  File "/home/bigtree/PycharmProjects/pytorch-mask-rcnn/model.py", line 569, in detection_target_layer
    crowd_ix = torch.nonzero(gt_class_ids < 0)[:, 0]
IndexError: too many indices for tensor of dimension 1

**Comment by xllau** [comment]
Might because you are using pytorch 0.4,  change into 0.3, the code if torch.nonzero(..) won't execute.

**Comment by buaaMars** [comment]
@xllau what I use is pytorch 0.3.
train a new model on coco with imagenet pre-trained model by this code for 3 epoch and evaluate the model saved in logs, you will find the error.

**Comment by fxia22** [comment]
Here is my solution: 
```
    if torch.nonzero(keep_bool).size()[0]:
        keep = torch.nonzero(keep_bool)[:,0]
    else:
        keep = torch.from_numpy(np.array([1]))
```
If the class_id is 0 it will be filtered out by next steps so it's fine. It's not an elegant solution but it works.

Tested on pytorch 0.4.1.
