### ISSUE TITLE
got this sad error in pytorch 0.4: TypeError: Expected bytes, got str

### ISSUE THREAD

**Issue by bigtreeljc** [multimodallearning/pytorch-mask-rcnn#34]
Checkpoint Path: /home/bigtree/PycharmProjects/pytorch-mask-rcnn/logs/coco20180706T2256/mask_rcnn_coco_{:04d}.pth
Epoch 1/40.
Traceback (most recent call last):
  File "coco.py", line 498, in <module>
    layers='heads')
  File "/home/bigtree/PycharmProjects/pytorch-mask-rcnn/model.py", line 1793, in train_model
    loss, loss_rpn_class, loss_rpn_bbox, loss_mrcnn_class, loss_mrcnn_bbox, loss_mrcnn_mask = self.train_epoch(train_generator, optimizer, self.config.STEPS_PER_EPOCH)
  File "/home/bigtree/PycharmProjects/pytorch-mask-rcnn/model.py", line 1822, in train_epoch
    for inputs in datagenerator:
  File "/home/bigtree/anaconda3/envs/tensorflow/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/bigtree/anaconda3/envs/tensorflow/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/bigtree/anaconda3/envs/tensorflow/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/bigtree/anaconda3/envs/tensorflow/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/bigtree/PycharmProjects/pytorch-mask-rcnn/model.py", line 1359, in __getitem__
    use_mini_mask=self.config.USE_MINI_MASK)
  File "/home/bigtree/PycharmProjects/pytorch-mask-rcnn/model.py", line 1162, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "coco.py", line 245, in load_mask
    image_info["width"])
  File "coco.py", line 304, in annToMask
    rle = self.annToRLE(ann, height, width)
  File "coco.py", line 290, in annToRLE
    rle = maskUtils.merge(rles)
  File "pycocotools/_mask.pyx", line 145, in pycocotools._mask.merge (pycocotools/_mask.c:3173)
  File "pycocotools/_mask.pyx", line 122, in pycocotools._mask._frString (pycocotools/_mask.c:2605)
TypeError: Expected bytes, got str

**Comment by bigtreeljc** [comment]
my bad, it's because I did not install pycocoapi. Somebody can close it now!!
