### ISSUE TITLE
Error while training using coco.py 

### ISSUE THREAD

**Issue by crazysal** [multimodallearning/pytorch-mask-rcnn#37]
Traceback (most recent call last):
 ```
 File "coco.py", line 501, in <module>
    layers='heads')
  File "/mnt/data/repos/pytorch-mask-rcnn/model.py", line 1803, in train_model
    loss, loss_rpn_class, loss_rpn_bbox, loss_mrcnn_class, loss_mrcnn_bbox, loss_mrcnn_mask = self.train_epoch(train_generator, optimizer, self.config.STEPS_PER_EPOCH)
  File "/mnt/data/repos/pytorch-mask-rcnn/model.py", line 1865, in train_epoch
    self.predict([images, image_metas, gt_class_ids, gt_boxes, gt_masks], mode='training')
  File "/mnt/data/repos/pytorch-mask-rcnn/model.py", line 1719, in predict
    detection_target_layer(rpn_rois, gt_class_ids, gt_boxes, gt_masks, self.config)
  File "/mnt/data/repos/pytorch-mask-rcnn/model.py", line 569, in detection_target_layer
    crowd_ix = torch.nonzero(gt_class_ids < 0)[:, 0]
IndexError: too many indices for tensor of dimension 1
```

**Comment by crazysal** [comment]
Complete terminal output : 

(pyt) ubuntu@cvp-saleem:/mnt/data/repos/pytorch-mask-rcnn$ python coco.py --dataset ../cocoapi/ --year 2017 train 

> Command:  train
> Model:  None
> Dataset:  ../cocoapi/
> Year:  2017
> Logs:  /mnt/data/repos/pytorch-mask-rcnn/logs
> Auto Download:  False
> 
> Configurations:
> BACKBONE_SHAPES                [[256 256]
>  [128 128]
>  [ 64  64]
>  [ 32  32]
>  [ 16  16]]
> BACKBONE_STRIDES               [4, 8, 16, 32, 64]
> BATCH_SIZE                     16
> BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
> DETECTION_MAX_INSTANCES        100
> DETECTION_MIN_CONFIDENCE       0.7
> DETECTION_NMS_THRESHOLD        0.3
> GPU_COUNT                      1
> IMAGENET_MODEL_PATH            /mnt/data/repos/pytorch-mask-rcnn/resnet50_imagenet.pth
> IMAGES_PER_GPU                 16
> IMAGE_MAX_DIM                  1024
> IMAGE_MIN_DIM                  800
> IMAGE_PADDING                  True
> IMAGE_SHAPE                    [1024 1024    3]
> LEARNING_MOMENTUM              0.9
> LEARNING_RATE                  0.001
> MASK_POOL_SIZE                 14
> MASK_SHAPE                     [28, 28]
> MAX_GT_INSTANCES               100
> MEAN_PIXEL                     [123.7 116.8 103.9]
> MINI_MASK_SHAPE                (56, 56)
> NAME                           coco
> NUM_CLASSES                    81
> POOL_SIZE                      7
> POST_NMS_ROIS_INFERENCE        1000
> POST_NMS_ROIS_TRAINING         2000
> ROI_POSITIVE_RATIO             0.33
> RPN_ANCHOR_RATIOS              [0.5, 1, 2]
> RPN_ANCHOR_SCALES              (32, 64, 128, 256, 512)
> RPN_ANCHOR_STRIDE              1
> RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
> RPN_NMS_THRESHOLD              0.7
> RPN_TRAIN_ANCHORS_PER_IMAGE    256
> STEPS_PER_EPOCH                16000
> TRAIN_ROIS_PER_IMAGE           200
> USE_MINI_MASK                  True
> USE_RPN_ROIS                   True
> VALIDATION_STEPS               50
> WEIGHT_DECAY                   0.0001
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> /mnt/data/repos/pytorch-mask-rcnn/model.py:1474: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
>   nn.init.xavier_uniform(m.weight)
> Loading weights  
> Weight file not found ...
> loading annotations into memory...
> 
> 
> 
> 
> 
> 
> 
> 
> 
> Done (t=11.50s)
> creating index...
> index created!
> INSTANCES BEING LOADED FROM ::::  <pycocotools.coco.COCO object at 0x7fd17e29fcf8>
> Image being loaded from  ../cocoapi//images/train2017
> 
> 
> 
> 
> 
> 
> loading annotations into memory...
> Done (t=0.33s)
> creating index...
> index created!
> INSTANCES BEING LOADED FROM ::::  <pycocotools.coco.COCO object at 0x7fd1793ff080>
> Image being loaded from  ../cocoapi//images/val2017
> loading annotations into memory...
> Done (t=0.35s)
> creating index...
> index created!
> INSTANCES BEING LOADED FROM ::::  <pycocotools.coco.COCO object at 0x7fd0c959af98>
> Image being loaded from  ../cocoapi//images/val2017
> Training network heads
> 
> Starting at epoch 1. LR=0.001
> 
> Checkpoint Path: /mnt/data/repos/pytorch-mask-rcnn/logs/coco20180724T2010/mask_rcnn_coco_{:04d}.pth
> Epoch 1/40.
> /home/ubuntu/anaconda3/envs/pyt/lib/python3.6/site-packages/scipy/ndimage/interpolation.py:583: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
>   "the returned array has changed.", UserWarning)
> /home/ubuntu/anaconda3/envs/pyt/lib/python3.6/site-packages/scipy/ndimage/interpolation.py:583: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
>   "the returned array has changed.", UserWarning)
> /home/ubuntu/anaconda3/envs/pyt/lib/python3.6/site-packages/scipy/ndimage/interpolation.py:583: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
>   "the returned array has changed.", UserWarning)
>
> Traceback (most recent call last):
>   File "coco.py", line 501, in <module>
>     layers='heads')
>   File "/mnt/data/repos/pytorch-mask-rcnn/model.py", line 1803, in train_model
>     loss, loss_rpn_class, loss_rpn_bbox, loss_mrcnn_class, loss_mrcnn_bbox, loss_mrcnn_mask = self.train_epoch(train_generator, optimizer, self.config.STEPS_PER_EPOCH)
>   File "/mnt/data/repos/pytorch-mask-rcnn/model.py", line 1865, in train_epoch
>     self.predict([images, image_metas, gt_class_ids, gt_boxes, gt_masks], mode='training')
>   File "/mnt/data/repos/pytorch-mask-rcnn/model.py", line 1719, in predict
>     detection_target_layer(rpn_rois, gt_class_ids, gt_boxes, gt_masks, self.config)
>   File "/mnt/data/repos/pytorch-mask-rcnn/model.py", line 569, in detection_target_layer
>     crowd_ix = torch.nonzero(gt_class_ids < 0)[:, 0]
> IndexError: too many indices for tensor of dimension 1

**Comment by ZhangGongjie** [comment]
I have met the same problem on Pytorch 0.4.0. Are there any solutions?

**Comment by jytime** [comment]
@ZhangGongjie @crazysal plz see [here](https://github.com/multimodallearning/pytorch-mask-rcnn/issues/24#issuecomment-406264734)

**Comment by ZhangGongjie** [comment]
Problem solved. Thank you!

**Comment by BPiepmatz** [comment]
Hey @ZhangGongjie I still receive the same error.  Even after changing it @jytime. The difference is that I want to train the network on the person class only and changed to "NUM_CLASS = 1+1". The strange thing is that I can train the network on all 80+1 COCO classes but not on a single one. I also got rid of the last layers of the back bone network to fit it to the classes. Would be nice if you guys have some idea what that could be.

best

> /pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [4,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [5,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [6,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [7,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "/home/cdr/anaconda3/envs/masterthesis/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-44a72dca93e1>", line 1, in <module>
    runfile('/media/cdr/WorkingFiles/Mthesis/mask-rcnn_0.4/coco.py', args='train --dataset=/media/cdr/WorkingFiles/Mthesis/mask-rcnn_0.4/ --year=2014 --model=coco', wdir='/media/cdr/WorkingFiles/Mthesis/mask-rcnn_0.4')
  File "/home/cdr/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/cdr/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/media/cdr/WorkingFiles/Mthesis/mask-rcnn_0.4/coco.py", line 573, in <module>
    layers='heads')
  File "/media/cdr/WorkingFiles/Mthesis/mask-rcnn_0.4/model.py", line 1832, in train_model
    train_generator, optimizer, self.config.STEPS_PER_EPOCH)
  File "/media/cdr/WorkingFiles/Mthesis/mask-rcnn_0.4/model.py", line 1901, in train_epoch
    target_deltas, mrcnn_bbox, target_mask, mrcnn_mask)
  File "/media/cdr/WorkingFiles/Mthesis/mask-rcnn_0.4/model.py", line 1156, in compute_losses
    mrcnn_bbox_loss = compute_mrcnn_bbox_loss(target_deltas, target_class_ids, mrcnn_bbox)
  File "/media/cdr/WorkingFiles/Mthesis/mask-rcnn_0.4/model.py", line 1103, in compute_mrcnn_bbox_loss
    positive_roi_ix = torch.nonzero(target_class_ids > 0)[:, 0]
RuntimeError: copy_if failed to synchronize: device-side assert triggered

**Comment by BPiepmatz** [comment]
Okay, for anyone also running in my issue: When you want to train on a subset of classes then you also have to change NUM_CLASSES and also have to provide the class ids in load_coco as a list.

example for class 1:

`dataset_train.load_coco(args.dataset, "train", year=args.year, auto_download=args.download, class_ids=[1])`
