### ISSUE TITLE
Value '[sm_61]' is not defined for option 'gpu-architecture'

### ISSUE THREAD

**Issue by menghuadeng** [multimodallearning/pytorch-mask-rcnn#38]
Hi, @lasseha ,
when I input the following command "nvcc -c -o nms_kernel.cu.o nms_kernel.cu -x cu -Xcompiler -fPIC -arch=[sm_61]" , it reported the "nvcc fatal   : Value '[sm_61]' is not defined for option 'gpu-architecture'" error. My cuda version is 9.0, my GPU is 1080. And I have installed the nvcc and add to the path. Thanks!

**Comment by botcs** [comment]
remove the brackets, and it will work

**Comment by sdw95927** [comment]
Just for others who may meet a similar issure, my GPU is P100, so I just tried "sm_61", "sm_60", "sm_52", "sm_50", and finally "sm_35" worked for me.

**Comment by menghuadeng** [comment]
Thank you@botcs @sdw95927  . I used "nvcc -c -o nms_kernel.cu.o nms_kernel.cu -x cu -Xcompiler -fPIC -arch=sm_61", then it work. Thank you very much.

**Comment by wgs123** [comment]
I meet  a problem,
building '_nms' extension
creating Release
creating Release\medicaldetectiontoolkit-master
creating Release\medicaldetectiontoolkit-master\cuda_functions
creating Release\medicaldetectiontoolkit-master\cuda_functions\nms_2D
creating Release\medicaldetectiontoolkit-master\cuda_functions\nms_2D\src
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWITH_CUDA -IC:\ProgramData\Anaconda3\lib\site-packages\torch\utils\ffi\..\..\lib\include -IC:\ProgramData\Anaconda3\lib\site-packages\torch\utils\ffi\..\..\lib\include\TH -IC:\ProgramData\Anaconda3\lib\site-packages\torch\utils\ffi\..\..\lib\include\THC -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" "-IC:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tc_nms.c /Fo.\Release\_nms.obj
_nms.c
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt.h(10) : fatal error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\distutils\_msvccompiler.py", line 423, in compile
    self.spawn(args)
  File "C:\ProgramData\Anaconda3\lib\distutils\_msvccompiler.py", line 542, in spawn
    return super().spawn(cmd)
  File "C:\ProgramData\Anaconda3\lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\ProgramData\Anaconda3\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\ProgramData\Anaconda3\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\BIN\\cl.exe' failed with exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\cffi\ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\setuptools\command\build_ext.py", line 78, in run
    _build_ext.run(self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\ProgramData\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\setuptools\command\build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "C:\ProgramData\Anaconda3\lib\distutils\_msvccompiler.py", line 425, in compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\BIN\\cl.exe' failed with exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 34, in <module>
    ffi.build()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\ffi\__init__.py", line 167, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\ffi\__init__.py", line 103, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cffi\api.py", line 723, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cffi\recompiler.py", line 1526, in recompile
    compiler_verbose, debug)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cffi\ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cffi\ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\BIN\\cl.exe' failed with exit status 2

**Comment by huangpan2507** [comment]
> 
> 
> remove the brackets, and it will work

it works for me，just do it

**Comment by tuttelikz** [comment]
hi!
Which [arch] shall i use for NVIDIA RTX3090 during:
`nvcc -c -o nms_kernel.cu.o nms_kernel.cu -x cu -Xcompiler -fPIC -arch=[arch]`
if i type `nvcc --list-gpu-code` command in linux terminal, it returns:
```
sm_35
sm_37
sm_50
sm_52
sm_53
sm_60
sm_61
sm_62
sm_70
sm_72
sm_75
sm_80
sm_86
```
cuda is `11.2`

**Comment by dppselena** [comment]
@wgs123  Hello,I also encountered the same question，have you solve it?

**Comment by dppselena** [comment]
@wgs123  Hello,I also encountered the same question，have you solve it?
