### ISSUE TITLE
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by miaoshuyu** [multimodallearning/pytorch-mask-rcnn#50]
when i do 'python build.py ',it got an error as follow.How can i solve it.
ce-code/pytorch-mask-rcnn/nms/src/nms.o /home/miaoshuyu/source-code/pytorch-mask-rcnn/nms/src/cuda/nms_kernel.cu.o -o ./_nms.so
gcc: error: /home/miaoshuyu/source-code/pytorch-mask-rcnn/nms/src/cuda/nms_kernel.cu.o: No such file or directory
Traceback (most recent call last):
  File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 34, in <module>
    ffi.build()
  File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1

**Comment by vasgaowei** [comment]
I faced the same problem, and I solved it by changing pytorch0.4.1 to pytorch0.4.0.

**Comment by infinite06** [comment]
> I faced the same problem, and I solved it by changing pytorch0.4.1 to pytorch0.4.0.
thx , it solve my problem.

**Comment by suzhengpeng** [comment]
> I faced the same problem, and I solved it by changing pytorch0.4.1 to pytorch0.4.0.

thanks for your answer

**Comment by dheerajnuka** [comment]
> when i do 'python build.py ',it got an error as follow.How can i solve it.
> ce-code/pytorch-mask-rcnn/nms/src/nms.o /home/miaoshuyu/source-code/pytorch-mask-rcnn/nms/src/cuda/nms_kernel.cu.o -o ./_nms.so
> gcc: error: /home/miaoshuyu/source-code/pytorch-mask-rcnn/nms/src/cuda/nms_kernel.cu.o: No such file or directory
> Traceback (most recent call last):
> File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 197, in link
> self.spawn(linker + ld_args)
> File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
> spawn(cmd, dry_run=self.dry_run)
> File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/spawn.py", line 36, in spawn
> _spawn_posix(cmd, search_path, dry_run=dry_run)
> File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
> % (cmd, exit_status))
> distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
> dist.run_command('build_ext')
> File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
> cmd_obj.run()
> File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
> self.build_extensions()
> File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
> self._build_extensions_serial()
> File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
> self.build_extension(ext)
> File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
> target_lang=language)
> File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
> extra_preargs, extra_postargs, build_temp, target_lang)
> File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 199, in link
> raise LinkError(msg)
> distutils.errors.LinkError: command 'gcc' failed with exit status 1
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "build.py", line 34, in
> ffi.build()
> File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/**init**.py", line 189, in build
> _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
> File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/**init**.py", line 111, in _build_extension
> outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
> File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
> compiler_verbose=verbose, debug=debug, **kwds)
> File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
> compiler_verbose, debug)
> File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
> outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
> File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
> raise VerificationError('%s: %s' % (e.**class**.**name**, e))
> cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1

I am also facing the same problem even after pytorch0.4.0 is installed

**Comment by 18810580125** [comment]
> > when i do 'python build.py ',it got an error as follow.How can i solve it.
> > ce-code/pytorch-mask-rcnn/nms/src/nms.o /home/miaoshuyu/source-code/pytorch-mask-rcnn/nms/src/cuda/nms_kernel.cu.o -o ./_nms.so
> > gcc: error: /home/miaoshuyu/source-code/pytorch-mask-rcnn/nms/src/cuda/nms_kernel.cu.o: No such file or directory
> > Traceback (most recent call last):
> > File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 197, in link
> > self.spawn(linker + ld_args)
> > File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
> > spawn(cmd, dry_run=self.dry_run)
> > File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/spawn.py", line 36, in spawn
> > _spawn_posix(cmd, search_path, dry_run=dry_run)
> > File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
> > % (cmd, exit_status))
> > distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
> > dist.run_command('build_ext')
> > File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
> > cmd_obj.run()
> > File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
> > self.build_extensions()
> > File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
> > self._build_extensions_serial()
> > File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
> > self.build_extension(ext)
> > File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
> > target_lang=language)
> > File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
> > extra_preargs, extra_postargs, build_temp, target_lang)
> > File "/home/miaoshuyu/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 199, in link
> > raise LinkError(msg)
> > distutils.errors.LinkError: command 'gcc' failed with exit status 1
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "build.py", line 34, in
> > ffi.build()
> > File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/**init**.py", line 189, in build
> > _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
> > File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/**init**.py", line 111, in _build_extension
> > outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
> > File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
> > compiler_verbose=verbose, debug=debug, **kwds)
> > File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
> > compiler_verbose, debug)
> > File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
> > outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
> > File "/home/miaoshuyu/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
> > raise VerificationError('%s: %s' % (e.**class**.**name**, e))
> > cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1
> 
> I am also facing the same problem even after pytorch0.4.0 is installed

You can try pytorch 0.3.0
