### ISSUE TITLE
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by dongzhang89** [multimodallearning/pytorch-mask-rcnn#51]
Does any one meet this problem, it come up after many batch trainning ?
_______________________________________________________________________________________________________________
Traceback (most recent call last):
  File "coco.py", line 498, in <module>
    layers='heads')
  File "/home/dong/dong/pytorch/2-mask-rcnn/model.py", line 1796, in train_model
    loss, loss_rpn_class, loss_rpn_bbox, loss_mrcnn_class, loss_mrcnn_bbox, loss_mrcnn_mask = self.train_epoch(train_generator, optimizer, self.config.STEPS_PER_EPOCH
  File "/home/dong/dong/pytorch/2-mask-rcnn/model.py", line 1858, in train_epoch
    self.predict([images, image_metas, gt_class_ids, gt_boxes, gt_masks], mode='training')
  File "/home/dong/dong/pytorch/2-mask-rcnn/model.py", line 1732, in predict
    mrcnn_class_logits, mrcnn_class, mrcnn_bbox = self.classifier(mrcnn_feature_maps, rois)
  File "/home/dong/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dong/zhangdong/pytorch/2-mask-rcnn/model.py", line 929, in forward
    x = pyramid_roi_align([rois]+x, self.pool_size, self.image_shape)
  File "/home/dong/dong/pytorch/2-mask-rcnn/model.py", line 436, in pyramid_roi_align
    y1, x1, y2, x2 = boxes.chunk(4, dim=1)
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by zccoder** [comment]
How do you solve it ?

**Comment by gaowu9595** [comment]
I also meet this problem.Do you solve it ?

**Comment by ETHRuiGong** [comment]
The same issue. Could you please explain how to solve it?

**Comment by ghost** [comment]
How do you solve this problem? I also met it....

**Comment by vividaner** [comment]
How to fix the issue? I also met it.

**Comment by saddam-94** [comment]
Did anyone solve this issue? I faced this issue. please let me know how to mitigate this issue.

**Comment by Swjtu-only** [comment]
i hava solve the problem,If it helps you, please give me a thumbs up,
And This problem can be merged  #24 
the .size() function in Pytorch 0.4 and above is different from Pytorch 0.3,
you can modify the model.py ，change .size() into .size()[0]
There are several changes that need to be made
568: if torch.nonzero(gt_class_ids < 0).size():
597: if torch.nonzero(positive_roi_bool).size():
656: if torch.nonzero(negative_roi_bool).size() and positive_count>0:
1056: if target_class_ids.size():
1074: if target_class_ids.size():
1104: if target_class_ids.size():
1716: if not rois.size():
1934: if not target_class_ids.size():
you can see my small experiment,In the following picture:
![微信图片_20191120221807](https://user-images.githubusercontent.com/24319933/69246638-073b5780-0be4-11ea-9ff1-3cc815db8032.png)

**Comment by Swjtu-only** [comment]
i hava solve the problem,If it helps you, please give me a thumbs up,
And This problem can be merged #24
The key to the problem is that  x.size() return True,x.size()[0] return False in Pytorch 0.4 and above.so
you can modify the model.py ，change .size() into .size()[0]
There are several changes that need to be made
568: if torch.nonzero(gt_class_ids < 0).size():
597: if torch.nonzero(positive_roi_bool).size():
656: if torch.nonzero(negative_roi_bool).size() and positive_count>0:
1056: if target_class_ids.size():
1074: if target_class_ids.size():
1104: if target_class_ids.size():
1716: if not rois.size():
1934: if not target_class_ids.size():
you can see my small experiment,In the following code:
>>> torch.__version__  
'1.0.0.dev20190401'
>>> x = torch.Tensor()
>>> if x.size():
...     print(x.size())
torch.Size([0])
>>> if x.size()[0]:
...     print(x.size()[0])
