### ISSUE TITLE
ERROR: RuntimeError: cuda runtime error (2) : out of memory

### ISSUE THREAD

**Issue by qq4060** [multimodallearning/pytorch-mask-rcnn#59]
~/pytorch-mask-rcnn$ python3 demo.py
Configurations:
BACKBONE_SHAPES                [[256 256]
 [128 128]
 [ 64  64]
 [ 32  32]
 [ 16  16]]
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     1
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0.7
DETECTION_NMS_THRESHOLD        0.3
GPU_COUNT                      1
IMAGENET_MODEL_PATH            /home/qq4060/pytorch-mask-rcnn/resnet50_imagenet.pth
IMAGES_PER_GPU                 1
IMAGE_MAX_DIM                  1024
IMAGE_MIN_DIM                  800
IMAGE_PADDING                  True
IMAGE_SHAPE                    [1024 1024    3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [123.7 116.8 103.9]
MINI_MASK_SHAPE                (56, 56)
NAME                           coco
NUM_CLASSES                    81
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1000
POST_NMS_ROIS_TRAINING         2000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (32, 64, 128, 256, 512)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.7
RPN_TRAIN_ANCHORS_PER_IMAGE    256
STEPS_PER_EPOCH                1000
TRAIN_ROIS_PER_IMAGE           200
USE_MINI_MASK                  True
USE_RPN_ROIS                   True
VALIDATION_STEPS               50
WEIGHT_DECAY                   0.0001

/home/qq4060/pytorch-mask-rcnn/model.py:1474: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(m.weight)
/usr/lib/python3/dist-packages/scipy/misc/pilutil.py:479: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if issubdtype(ts, int):
/usr/lib/python3/dist-packages/scipy/misc/pilutil.py:482: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif issubdtype(type(size), float):
/home/qq4060/pytorch-mask-rcnn/model.py:1595: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  molded_images = Variable(molded_images, volatile=True)
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "demo.py", line 74, in <module>
    results = model.detect([image])
  File "/home/qq4060/pytorch-mask-rcnn/model.py", line 1598, in detect
    detections, mrcnn_mask = self.predict([molded_images, image_metas], mode='inference')
  File "/home/qq4060/pytorch-mask-rcnn/model.py", line 1645, in predict
    layer_outputs.append(self.rpn(p))
  File "/home/qq4060/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qq4060/pytorch-mask-rcnn/model.py", line 879, in forward
    x = self.relu(self.conv_shared(self.padding(x)))
  File "/home/qq4060/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qq4060/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58

**Comment by LaiPiXiong** [comment]
Try to comment out visualization code.

**Comment by qq4060** [comment]
THANK YOU! 
your mean  comment the end of this visualization code ?
# Visualize results
#r = results[0]
#visualize.display_instances(image, r['rois'], r['masks'], r['class_ids'],
  #                          class_names, r['scores'])
#plt.show()
BUT it still has this problem of OUT OF MEMORY

**Comment by qq4060** [comment]
THANK YOU!
your mean comment the end of this visualization code ?
#Visualize results

#r = results[0]
#visualize.display_instances(image, r['rois'], r['masks'], r['class_ids'],
#class_names, r['scores'])
#plt.show()
BUT it still has this problem of OUT OF MEMORY

**Comment by LaiPiXiong** [comment]
And change read image as follows:
`    with torch.set_grad_enabled(False):
        image = cv2.imread(file_name)`
Maybe you need to change volatile in model.py to torch.set_grad_enabled as above

**Comment by qq4060** [comment]
> And change read image as follows:
> ` with torch.set_grad_enabled(False): image = cv2.imread(file_name)`
> Maybe you need to change volatile in model.py to torch.set_grad_enabled as above

Thanks....

**Comment by wyk0517** [comment]
> > And change read image as follows:
> > ` with torch.set_grad_enabled(False): image = cv2.imread(file_name)`
> > Maybe you need to change volatile in model.py to torch.set_grad_enabled as above
> 
> Thanks....



> And change read image as follows:
> ` with torch.set_grad_enabled(False): image = cv2.imread(file_name)`
> Maybe you need to change volatile in model.py to torch.set_grad_enabled as above

HI
Do you know how to solve this problem? 
I don't understand the answer of LaiPiXiong, can you give some more details?

**Comment by qq4060** [comment]
no
I did not solve this ,consider to buy a new GPU

**Comment by LaiPiXiong** [comment]
I mean, volatile=True doesn't work on pytorch0.4.0. You need to change to code as above

**Comment by ocean1211** [comment]
> I mean, volatile=True doesn't work on pytorch0.4.0. You need to change to code as above

But we meet the same question with pytorch 0.3.0.......

**Comment by LaiPiXiong** [comment]
You first need to comment  out visualization code.

**Comment by ocean1211** [comment]
> You first need to comment out visualization code.

Thank you, and we finally find the reason. We use the same GPU with others on the server, so the memory runs out...

**Comment by CzJaewan** [comment]
volatile = True -> requires_grad=True

**Comment by zhaozhongch** [comment]
Here comes a late reply.
Out of memory problem mostly is because your GPU sucks like mine, an Nvidia 1050 with 4GB memory. This may not be enough for training but should be enough for validation.
During the training process, you need to get the gradient for backpropagation but during the validation process, you don't need it because you just want to use the trained model, the gradient is not required.  So in the `demo.py`, you simply need to modify the code
```
    # Run detection
    results = model.detect([image])

    # Visualize results
    r = results[0]
    print('class id is \n', r['class_ids'])
    visualize.display_instances(image, r['rois'], r['masks'], r['class_ids'],
                                class_names, r['scores'])
    plt.show()
```

to

```
with torch.no_grad():
    # Run detection
    results = model.detect([image])

    # Visualize results
    r = results[0]
    print('class id is \n', r['class_ids'])
    visualize.display_instances(image, r['rois'], r['masks'], r['class_ids'],
                                class_names, r['scores'])
    plt.show()
```
