### ISSUE TITLE
TypeError: dist must be a Distribution instance

### ISSUE THREAD

**Issue by chaerlo** [multimodallearning/pytorch-mask-rcnn#81]
python3.6 build.py
Traceback (most recent call last):
  File "build.py", line 30, in <module>
    extra_objects=extra_objects
  File "/home/xx/enviorment/python3.6/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 228, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/home/xx/enviorment/python3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 127, in __init__
    _Command.__init__(self, dist)
  File "/home/xx/enviorment/python3.6/lib/python3.6/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance

**Comment by chaerlo** [comment]
I am encountered with a problem when building nms.
Really thanks for giving any suggestions or help.

**Comment by JarvisKevin** [comment]
Maybe you can try PyTorch 0.3

**Comment by Swjtu-only** [comment]
i ment the same problem.

**Comment by Swjtu-only** [comment]
i meet the same problem.

**Comment by Swjtu-only** [comment]
when i change my 0.3.1 pytorch version,i solve the problem.

**Comment by huangpan2507** [comment]
> 
> 
> when i change my 0.3.1 pytorch version,i solve the problem.

can u show your environment ？ cuda cudnn  torchvison  pytorch version？thanks a lot

**Comment by huangpan2507** [comment]
> 
> 
> when i change my 0.3.1 pytorch version,i solve the problem.

when i try to install pytorch ==0.3.1 it show that cuda=8.x version，but my cuda=10.1， it make me upset

**Comment by Swjtu-only** [comment]
@huangpan2507   Here is my environment lists:
h5py==2.8.0
imageio==2.5.0
imagesize==0.7.1
matplotlib==3.0.3
numpy==1.16.3
opencv-python==3.4.3.18
pandas==0.18.1
Pillow==6.2.0
PyYAML==5.1
scikit-image==0.15.0
scikit-learn==0.19.1
scikit-surprise==1.0.4
scipy==1.2.1
six==1.12.0
sklearn==0.0
tensorboardX==1.4
torch==0.4.0
torchvision==0.2.1
plyfile==0.6

you can write to txt,and then pip install -u *.txt.
Oh,python is 3.5.

**Comment by seanpan0111** [comment]
How to solve this problem if we do not upgrade torch version from 1.2.0 to 0.4.0?

**Comment by ghost** [comment]
How to solve this problem if we do not degrade torch version from 1.2.0 to 0.4.0?

**Comment by henbucuoshanghai** [comment]
teh same error   
/envs/frcnn/lib/python3.6/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
